version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker/cypress"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/docker/php"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/docker/nginx"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/api"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"
