parameters:
    app.feeds:
        - https://bbs.archlinux.de/extern.php?action=feed&fid=362&type=atom&order=posted
        - https://bbs.archlinux.de/extern.php?action=feed&fid=257&type=atom&order=posted
        - http://www.atsutane.de/atom.xml
        - http://5in4.de/blog/category/arch-linux/feed/atom/
        - https://trompetenkaefer.wordpress.com/tag/archlinux/feed/atom/
        - https://www.uninformativ.de/blog/feeds/de.atom
        - https://yhaupenthal.org/linux.xml
        - https://blog.stefan-betz.net/categories/arch/feed.atom
        - https://www.loggn.de/tag/planet-archlinux-de/feed/atom/
        - https://edermi.github.io/post/index.xml
