twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    date:
        format: 'd.m.Y H:i'
    number_format:
        decimal_point: ','
        thousands_separator: '.'
