#index:
#    path: /
#    controller: App\Controller\DefaultController::index

external_start:
    path: /
    host: www.archlinux.de
    schemes: ['https']

external_packages:
    path: /packages
    host: www.archlinux.de
    schemes: ['https']

external_download:
    path: /download
    host: www.archlinux.de
    schemes: ['https']

external_privacypolicy:
    path: /privacy-policy
    host: www.archlinux.de
    schemes: ['https']

external_impressum:
    path: /impressum
    host: www.archlinux.de
    schemes: ['https']

external_forum:
    path: /
    host: bbs.archlinux.de
    schemes: ['https']

external_wiki:
    path: /
    host: wiki.archlinux.de
    schemes: ['https']

external_aur:
    path: /
    host: aur.archlinux.de
    schemes: ['https']
