name: security

on:
  schedule:
    - cron: '0 5 */1 * *'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: make install
      - run: make test-security
